ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'ADMIN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'NURSERY_HEAD';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'PRIMARY_HEAD';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'PRINCIPAL';
